### ISSUE TITLE
token written to a file

### ISSUE THREAD

**Issue by xeaone** [j-mendez/dfirestore#6]
Why is the token written to a file?

https://github.com/j-mendez/dfirestore/blob/a62b94fcffddcdae8fdcb3b65798657477f7cfbc/config.ts#L65-L70

**Comment by j-mendez** [comment]
@vokeio Hi, if you are going to run the `refreshToken` the operation is done in a separate process and instead of communicating between split processes for this the idea was to save it to a file where only the creator has `read` and `write` access to use and to also allow the program auto manage the access token upon restarts instead of hard logging in where it can look at the token `exp` before needing to refresh etc.. Firebase by default expires tokens I think in 15 mins so the logic for the handling could be improved ( did it really quick for a small project ). I was using the methods in a manner where I would configure the token once in one step then use the dfirestore willingly via `CLI`. Can look into removing the write usage and just hard require env variables that should be set.

https://github.com/j-mendez/dfirestore/blob/a62b94fcffddcdae8fdcb3b65798657477f7cfbc/config.ts#L164.

**Comment by j-mendez** [comment]
@vokeio Going to remove the storing to the file for the CLI to have its own entry point where it can isolate the requirements as needed. Thanks for the issue! Will send this updated in the next release.

**Comment by j-mendez** [comment]
@vokeio [fixed](https://github.com/j-mendez/dfirestore/commit/f98f0ab7adb66d401883638785ef26c9026dc6d7) in v[v0.3.8](https://github.com/j-mendez/dfirestore/tree/v0.3.8). Thanks again!
